# Permalinks
permalink: archives/:year/:month/:title.html
markdown: kramdown

# Setup
title:               The Long Way
tagline:             'by Caleb Bassett'
description:         'There's no shortcut to goodness, truth, and beauty. But the long way is worth taking.''
url:                 http://crbassett.com
baseurl:             ''
paginate:            5

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name: Caleb Bassett
  url: https://twitter.com/crbassett
  email: caleb.bassett@gmail.com

# Custom vars

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives
  
jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
  permalinks:
    year: /archives/:year/
    month: /archives/:year/:month/
    category: /archives/cateogry/:name/