# Permalinks
permalink: date
markdown: kramdown

# Setup
title:               The Long Way
tagline:             'by Caleb Bassett'
description:         'There are no shortcuts to goodness, truth, and beauty—you must take the long way. This is a blog on the topics of theology, philosophy, and vocation.'
url:                 http://crbassett.com
# baseurl:             '/'
paginate:            5

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Caleb Bassett
  url:               https://twitter.com/crbassett
  email:             caleb.bassett@gmail.com

# Custom vars

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives
  
jekyll-archives:
  enabled: all
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    tag: tag-archive-layout
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
